### ISSUE TITLE
PM2 running more than 1 clustered process

### ISSUE THREAD

**Issue by rodenj1** [JakeH/pm2-cluster-prometheus#1]
First off, just wanted to say I have been looking for something like this for a while!  Nice work!

It looks like as part of your metric gathering process that you send a message to all PM2 controlled process to report their stats and this works great if you only have 1 clustered process running in PM2.  If you have multiple, it sends a request to all and waits for a reply.  If the other process is not running your module, it does not respond causing a timeout.  If it is running your module, it will inadvertently report stats for a process a different process.  I was wondering if you could add a filter to only send a message to process with the same process name "process.env.name".  I figure a quick filter under getProcList would do the trick.  :)

**Comment by JakeH** [comment]
You're absolutely right, it should filter out other pm2 processes.

It might be a couple of days before I can update this though.

**Comment by JakeH** [comment]
A couple of days, or 7 hours. 

NPM package version is 1.0.6. Please let me know if this works for you now.

**Comment by rodenj1** [comment]
Awesome!  Thank you!

John
