### ISSUE TITLE
PM2 Dependency Outdated

### ISSUE THREAD

**Issue by chalbersma** [JakeH/pm2-cluster-prometheus#5]
https://github.com/JakeH/pm2-cluster-prometheus/blob/ecffcc61de63cf4004e439b43d406dd54f6154f0/package.json#L29

I was looking at resolving an issue in one of our projects (specifically [GHSA-vh95-rmgr-6w4m](https://github.com/advisories/GHSA-vh95-rmgr-6w4m)). And this pm2 version relies on an outdated version of mkdirp that relies on minimist 0.0.8.

What's the feasibility of bumping this dependency to the latest pm2?

**Comment by JakeH** [comment]
I've moved both pm2 and prom-client to peerDependencies, and included their latest major version in the semver range. The new package was published as 2.0.0 (https://www.npmjs.com/package/pm2-cluster-prom/v/2.0.0). 

Please give that a try.

**Comment by chalbersma** [comment]
@JakeH Thanks! I believe that did it!
